### ISSUE TITLE
set error

### ISSUE THREAD

**Issue by KeKsBoTer** [KeKsBoTer/setlx2python#24]
```python
import setlx


@setlx.procedure
def power(m, n):
    r = m
    for i in setlx.Set(range(2, n + 1)):
        r = r * m
    return r


for n in list(range(1, 64 + 1)):
    setlx.print(power(2, n))
    setlx.print(power(3, n))
```
Output:
```
Traceback (most recent call last):
  File ".\examples\algorithms\power-naive.py", line 13, in <module>
    setlx.print(power(2, n))
  File "c:\users\simon\projects\setlpy\setlx\decorators.py", line 59, in decorator
    return func(*args, **kwargs)
  File ".\examples\algorithms\power-naive.py", line 7, in power
    for i in setlx.Set(range(2, n + 1)):
  File "c:\users\simon\projects\setlpy\setlx\set.py", line 26, in __iter__
    self.tree.current_node = self.tree[0]  # minimum of the tree
  File "c:\users\simon\projects\setlpy\setlx\tree.py", line 31, in __getitem__
    return self.root.__getitem__(index)
AttributeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by daniel-scholz** [comment]
does not occur after recent PR  [Dev/set #1](https://github.com/daniel-scholz/setlpy/pull/1/)
